# Generated by Django 5.0.2 on 2024-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='factors',
            options={'ordering': ['id'], 'verbose_name': 'factor', 'verbose_name_plural': 'factors'},
        ),
        migrations.AddField(
            model_name='factors',
            name='title',
            field=models.CharField(default='new factor', max_length=255, verbose_name='factor title'),
        ),
    ]
