# Generated by Django 5.0.2 on 2024-02-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_choice_choice_alter_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='new response', max_length=255, verbose_name='response')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
