# Generated by Django 5.0.2 on 2024-02-28 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_category_owner_questionnaires_owner_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionnaires',
            new_name='Questionnaire',
        ),
        migrations.AddField(
            model_name='response',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
    ]
