# Generated by Django 5.0.2 on 2024-02-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_rename_questionnaires_questionnaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='common_responses',
            field=models.ManyToManyField(blank=True, to='questionnaire.responsetemplate'),
        ),
    ]
