# Generated by Django 5.0.2 on 2024-02-29 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_remove_question_common_responses_question_responses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.factors'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questionnaire'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='responses',
        ),
        migrations.AddField(
            model_name='question',
            name='responses',
            field=models.ManyToManyField(help_text='Select possible responses for this question', related_name='questions', to='questionnaire.response', verbose_name='possible responses'),
        ),
    ]
