# Generated by Django 5.0.2 on 2024-02-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_alter_question_factor_alter_question_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
    ]
