# Generated by Django 5.0.2 on 2024-02-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instructions_text',
            field=models.CharField(default='input your instructions', max_length=5000, verbose_name='instructions text'),
        ),
    ]
