# Generated by Django 5.0.2 on 2024-02-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_alter_instruction_instructions_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='title',
            field=models.CharField(default='new instruction', max_length=255, verbose_name='instruction title'),
        ),
    ]
